force-app/main/default/objects/Grant_Solicitation__c/Grant_Solicitation__c.object-meta.xml
<CustomObject>
    <label>Grant/Solicitation</label>
    <nameField>
        <label>Grant/Solicitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Solicitation__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The program managing this solicitation.</description>
    <inlineHelpText>The program managing this solicitation.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Solicitation</relationshipLabel>
    <relationshipName>Program_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Solicitation2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation__c/fields/Solicitation_Manager__c.field-meta.xml
<CustomField>
    <fullName>Solicitation_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solicitation Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Solicitation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Draft, Open, or Closed. 

Draft: Solicitation creation and configuration stage. Nothing is exposed to the public. 
Open: Solicitation is open to the public and visible on the Current Funding Opportunities website.
Closed: Solicitation is closed and nDraft, Open, or Closed. 
Draft: Solicitation creation and configuration stage. Nothing is exposed to the public. 
Open: Solicitation is open to the public and visible on the website.
Closed: Solicitation is closed and not visible on the website.ot visible on the Current Funding Opportunities website.Solicitations Status is set to &quot;Closed&quot; automatically exactly at 5 pm on the day of the latest round due date. 
 A change mod is needed to set it back to open.

Canceled status SF-30800</description>
    <inlineHelpText>Draft: Creation and config stage. Nothing is shown to the public. 
Open: Open to the public and visible on website.
Closed: Closed and not visible on the website.Closed automatically at 3pm on the day of the latest round due date. Change mod to re-open</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Solicitation_Rounds__c/Grant_Solicitation_Rounds__c.object-meta.xml
<CustomObject>
    <label>Grant/Solicitation Rounds</label>
    <nameField>
        <label>Round Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant/Solicitation Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Solicitation_Rounds__c/fields/Solicitation__c.field-meta.xml
<CustomField>
    <fullName>Solicitation__c</fullName>
    <label>Solicitation</label>
    <referenceTo>Grant_Solicitation__c</referenceTo>
    <relationshipLabel>Solicitation Rounds</relationshipLabel>
    <relationshipName>Solicitation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation_Rounds__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Round status does not change in any way except manually. The &quot;Open&quot; round with the closest due date is automatically the round which submissions are held.</description>
    <inlineHelpText>Round status does not change in any way except manually. The &quot;Open&quot; round with the closest due date is automatically the round which submissions are held.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Content__c/Program_Content__c.object-meta.xml
<CustomObject>
    <description>This object will act as a template to hold program level contents like List of applicable documents</description>
    <label>Program Content</label>
    <nameField>
        <displayFormat>PRGC-{00000}</displayFormat>
        <label>Program Content Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Content__c/fields/Grant_Solicitation__c.field-meta.xml
<CustomField>
    <fullName>Grant_Solicitation__c</fullName>
    <label>Solicitation</label>
    <referenceTo>Grant_Solicitation__c</referenceTo>
    <relationshipLabel>Program Contents</relationshipLabel>
    <relationshipName>Program_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Content__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal_Content__c/Proposal_Content__c.object-meta.xml
<CustomObject>
    <label>Proposal Content</label>
    <nameField>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Proposal Content Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal_Invoice__c/Proposal_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proposal Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Program Review</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent to Finance</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Finance Approved</fullName>
            </value>
            <value>
                <fullName>Pending Audit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeliverablesAndMilestonesTest.cls
@isTest
private class DeliverablesAndMilestonesTest {
    @TestSetup
    static void makeData(){
        Program__c program = new Program__c();
        program.Name = 'TestProg';
        insert program;

        Grant_Solicitation__c grant = new Grant_Solicitation__c();
        grant.Name = 'TestGrant';
        grant.Program__c = program.Id;
        grant.Solicitation_Manager__c = UserInfo.getUserId();
        grant.Program_Manager__c = UserInfo.getUserId();

        insert grant;

        Grant_Solicitation_Rounds__c grantRound = new Grant_Solicitation_Rounds__c(Name = 'TestGrantRound',Solicitation__c = grant.Id);
        insert grantRound;

        Grant_Solicitation_Group__c grantGroup = new Grant_Solicitation_Group__c(Name = 'TestGrantGroup',Grant_Solicitation_Round__c = grantRound.Id);
        insert grantGroup;

        List<Program_Content__c> programCont =  new List<Program_Content__c>();
        Id deliverablesId = Schema.SObjectType.Program_Content__c.getRecordTypeInfosByName().get('Deliverables').getRecordTypeId();
        Id milestonesId = Schema.SObjectType.Program_Content__c.getRecordTypeInfosByName().get('Milestones').getRecordTypeId();
        Id tasksId = Schema.SObjectType.Program_Content__c.getRecordTypeInfosByName().get('Tasks').getRecordTypeId();

        programCont.add(new Program_Content__c(Object_Name__c = 'TestProgram deliverables', Grant_Solicitation__c = grant.Id, RecordTypeId = deliverablesId));
        programCont.add(new Program_Content__c(Object_Name__c = 'TestProgram milestones', Grant_Solicitation__c = grant.Id, RecordTypeId = milestonesId));
        programCont.add(new Program_Content__c(Name__c = 'TestProgram tasks', Grant_Solicitation__c = grant.Id, RecordTypeId = tasksId));
        insert programCont;

        //Proposal
        Proposal__c proposal = new Proposal__c(Name = 'TestProposal',Grant_Solicitation__c = grant.Id,Grant_Solicitation_Rounds__c = grantRound.Id ,Grant_Solicitation_Group__c =grantGroup.Id);
        insert proposal;

        //Invoice
        Proposal_Invoice__c proposalInvoice = new Proposal_Invoice__c(Name__c = 'TestInvoice',Proposal__c = proposal.Id,Proposal_Content__c = [SELECT Id FROM Proposal_Content__c WHERE Name__c = 'TestProgram milestones'].Id);
        insert proposalInvoice;

        //Budget 
        Budget__c budget = new Budget__c(Name = 'TestBudget', Proposal__c = proposal.Id);
        insert budget;

        //Document insert
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion'); 
            
        ContentVersion contentVersion_1 = new ContentVersion(
            Title='TestDocument', 
            PathOnClient ='Test.jpg',
            VersionData = bodyBlob, 
            origin = 'H'
        );
        insert contentVersion_1;
        
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId 
                        FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = [SELECT Id FROM Proposal_Content__c WHERE Name__c = 'TestProgram deliverables'].Id;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        insert contentlink;
    }   
    //Get proposal data
    @isTest
    static void retriveProposalcontentsTest(){
        Proposal__c testData = [SELECT Id FROM Proposal__c Where Name = 'TestProposal' LIMIT 1];
        List<Proposal_Content__c> proposalTest = DeliverablesAndMilestones.retriveProposalcontents(testData.Id);
        
        System.assertEquals('TestProgram milestones',proposalTest[0].Name__c);
    }
    //Get budgget of proposal
    @isTest
    static void getBudgetofProposalTest(){
        Proposal__c testData = [SELECT Id FROM Proposal__c Where Name = 'TestProposal' LIMIT 1];
        List<Budget__c> budgetTest = DeliverablesAndMilestones.getBudgetofProposal(testData.Id);
        
        System.assertEquals('TestBudget',budgetTest[0].Name);
    }
    //Get Invoice
    @isTest
    static void getInvoicesTest(){
        Proposal_Content__c testData = [SELECT Id FROM Proposal_Content__c WHERE Name__c = 'TestProgram milestones' LIMIT 1];

        String invoicesString = DeliverablesAndMilestones.getInvoices(testData.Id);
        List<InvoiceWrapper> invoicesTest = (List<InvoiceWrapper>)JSON.deserialize(invoicesString, List<InvoiceWrapper>.class);
        
        System.assertEquals(1,invoicesTest.size());
    }
    //Document 
    @isTest
    static void getDocumentDataTest(){
        Proposal_Content__c testData = [SELECT Id FROM Proposal_Content__c WHERE Name__c = 'TestProgram deliverables' LIMIT 1];
        String documnetString = JSON.serialize(DeliverablesAndMilestones.getDocumentData(testData.Id));
        List<DocumentUploadsWrapper> documnetTest = (List<DocumentUploadsWrapper>)JSON.deserialize(documnetString, List<DocumentUploadsWrapper>.class);
        
        System.assertEquals('TestDocument.JPG',documnetTest[0].fileName);
    }
    //Submitted proposal 
    @isTest
    static void setSumbittedDateProposalContentTest(){
        Proposal_Content__c newProposalContent = [SELECT Id,Status__c,Submitted_Date__c FROM Proposal_Content__c Where Name__c = 'TestProgram deliverables' LIMIT 1];

        DeliverablesAndMilestones.setSumbittedDateProposalContent(newProposalContent.Id);
        List<Proposal_Content__c> testPc = [SELECT Id,Status__c,Submitted_Date__c FROM Proposal_Content__c Where Name__c = 'TestProgram deliverables' LIMIT 1];
        
        System.assertEquals('Submitted',testPc[0].Status__c);
        System.assertEquals(date.today(),testPc[0].Submitted_Date__c);
    }
    //Update invoice
    @isTest
    static void updateInvoiceTest(){
        Proposal_Invoice__c newProposalInvoice = [SELECT Id FROM Proposal_Invoice__c Where Name__c = 'TestInvoice' LIMIT 1];
        InvoiceWrapper invoiceWrapper = new InvoiceWrapper();
        invoiceWrapper.Id = newProposalInvoice.Id;
        invoiceWrapper.Name = 'Test Invoice Change';
        invoiceWrapper.Amount = 200;
        String invoiceWrapperString = JSON.serialize(DeliverablesAndMilestones.updateInvoice(JSON.serialize(invoiceWrapper)));
        InvoiceWrapper invoiceWrapperTest = (InvoiceWrapper)JSON.deserialize(invoiceWrapperString, InvoiceWrapper.class);
        
        System.assertEquals('Test Invoice Change',invoiceWrapperTest.Name);
        System.assertEquals(200,invoiceWrapperTest.Amount);

    }

    public class DocumentUploadsWrapper {
        @AuraEnabled Public String key;
        @AuraEnabled Public String title;
        @AuraEnabled Public String fileName;
        @AuraEnabled Public Date CreatedDate;
        @AuraEnabled Public String ContentDocId;
        @AuraEnabled Public String ContentVerId;
        @AuraEnabled Public Boolean showFiles;
    }

  public class InvoiceWrapper {
      @AuraEnabled Public String Id;
      @AuraEnabled Public String AutoNumber;
      @AuraEnabled Public String Name;
      @AuraEnabled Public Decimal Amount;
      @AuraEnabled Public Date Invoice_Date;
      @AuraEnabled Public String Status;
      @AuraEnabled Public Boolean showEdit;
      @AuraEnabled Public String Proposal;
      @AuraEnabled Public String Proposal_Content;
      @AuraEnabled Public String Budget_Name;
      @AuraEnabled Public String Budget_Id;
  }
}