force-app/main/default/objects/Grant_Solicitation__c/Grant_Solicitation__c.object-meta.xml
<CustomObject>
    <label>Grant/Solicitation</label>
    <nameField>
        <label>Grant/Solicitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Solicitation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The end of the proposal submission period.</description>
    <inlineHelpText>The end of the proposal submission period. This field is used to move solicitations onto the closed funding opportunity page after this date (not at 3PM since there is no time on this field).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Draft, Open, or Closed. 

Draft: Solicitation creation and configuration stage. Nothing is exposed to the public. 
Open: Solicitation is open to the public and visible on the Current Funding Opportunities website.
Closed: Solicitation is closed and nDraft, Open, or Closed. 
Draft: Solicitation creation and configuration stage. Nothing is exposed to the public. 
Open: Solicitation is open to the public and visible on the website.
Closed: Solicitation is closed and not visible on the website.ot visible on the Current Funding Opportunities website.Solicitations Status is set to &quot;Closed&quot; automatically exactly at 5 pm on the day of the latest round due date. 
 A change mod is needed to set it back to open.

Canceled status SF-30800</description>
    <inlineHelpText>Draft: Creation and config stage. Nothing is shown to the public. 
Open: Open to the public and visible on website.
Closed: Closed and not visible on the website.Closed automatically at 3pm on the day of the latest round due date. Change mod to re-open</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Solicitation_Rounds__c/Grant_Solicitation_Rounds__c.object-meta.xml
<CustomObject>
    <label>Grant/Solicitation Rounds</label>
    <nameField>
        <label>Round Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant/Solicitation Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Solicitation_Rounds__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Proposal Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation_Rounds__c/fields/Solicitation__c.field-meta.xml
<CustomField>
    <fullName>Solicitation__c</fullName>
    <label>Solicitation</label>
    <referenceTo>Grant_Solicitation__c</referenceTo>
    <relationshipLabel>Solicitation Rounds</relationshipLabel>
    <relationshipName>Solicitation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation_Rounds__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Round status does not change in any way except manually. The &quot;Open&quot; round with the closest due date is automatically the round which submissions are held.</description>
    <inlineHelpText>Round status does not change in any way except manually. The &quot;Open&quot; round with the closest due date is automatically the round which submissions are held.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard__c/Scorecard__c.object-meta.xml
<CustomObject>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard__c/fields/Assign_To_User__c.field-meta.xml
<CustomField>
    <fullName>Assign_To_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scorecard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Grant_Solicitation__c.field-meta.xml
<CustomField>
    <fullName>Grant_Solicitation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant/Solicitation</label>
    <referenceTo>Grant_Solicitation__c</referenceTo>
    <relationshipLabel>Scorecard</relationshipLabel>
    <relationshipName>Scorecard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Scorecard</relationshipLabel>
    <relationshipName>Scorecard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Scored_Points__c.field-meta.xml
<CustomField>
    <fullName>Scored_Points__c</fullName>
    <label>Scored Points</label>
    <summarizedField>Scorecard_Metric__c.Points__c</summarizedField>
    <summaryFilterItems>
        <field>Scorecard_Metric__c.Layout_Type__c</field>
        <operation>equals</operation>
        <value>Field</value>
    </summaryFilterItems>
    <summaryForeignKey>Scorecard_Metric__c.Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Grants_ProposalReviewController.cls
public with sharing class Grants_ProposalReviewController {
    
    @AuraEnabled(cacheable=true)
    public static List<Grant_Solicitation_Rounds__c> getSolicitationRoundRecords(){
        return new List<Grant_Solicitation_Rounds__c>([SELECT Id, Name, Solicitation__c, Solicitation__r.Name, Solicitation__r.No_of_Proposals_to_review__c,Solicitation__r.End_Date__c,(Select Id from Projects__r) FROM Grant_Solicitation_Rounds__c
        WHERE Solicitation__r.Due_Date__c > TODAY WITH SECURITY_ENFORCED ORDER BY Solicitation__r.Name, Name]);
    }

    @AuraEnabled
    public static List<Proposal__c> getProposalsByStatus(String status, String grantId, String solRoundId){
        String queryStr = 'SELECT Id, Primary_Contractor_Account__r.Name, Proposal_Number__c,Requested_Amount__c, Completed_Date__c, Status__c, Grant_Solicitation__r.Name,Grant_Solicitation_Group__r.Name FROM Proposal__c'
                        + ' WHERE Grant_Solicitation__c =: grantId AND Grant_Solicitation_Rounds__c =: solRoundId AND Status__c != \'Draft\'  ';

        if(!status.equalsIgnoreCase('all')){
            queryStr = queryStr + ' AND Status__c =: status';
        }
        queryStr = queryStr + ' WITH SECURITY_ENFORCED ORDER BY Proposal_Number__c';
        return Database.query(queryStr);
    }

    @AuraEnabled
    public static List<Scorecard__c> getScorecards(String proposalRecId){
        return new List<Scorecard__c>([SELECT Id, Assign_To_User__c, Assign_To_User__r.Name, Assign_To_User__r.FullPhotoUrl, Assign_To_User__r.Email, 
        LastModifiedDate, Status__c, Scored_Points__c, Proposal__r.Proposal_Average_Score__c FROM Scorecard__c 
        WHERE Proposal__c =: proposalRecId WITH SECURITY_ENFORCED]);
    }

    @AuraEnabled(cacheable=true)
    public static Map<ID, String> getRelatedFilesByRecordId(String recordId){
        List<ContentDocumentLink> files = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId];
        List<ID> fileIDs = new List<ID>();
        for (ContentDocumentLink docLink : files) {
            fileIDs.add(docLink.ContentDocumentId);
        }
    
        List<ContentVersion> docs = [SELECT ContentDocumentId, Title FROM ContentVersion WHERE ContentDocumentId IN : fileIDs];
        Map<ID, String> mapIdTitle = new Map<ID, String>();
        for (ContentVersion docLink : docs) {
            mapIdTitle.put(docLink.ContentDocumentId, docLink.Title);
        }
        return mapIdTitle;
    }
}