force-app/main/default/objects/Grant_Solicitation__c/Grant_Solicitation__c.object-meta.xml
<CustomObject>
    <label>Grant/Solicitation</label>
    <nameField>
        <label>Grant/Solicitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Solicitation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PGRM</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>PCMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Solicitation__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>S-00704: Description text for Solicitation.</description>
    <inlineHelpText>Description of this solicitation. This field will be displayed on the Current Funding Opportunities &apos;Solicitation Detail&apos; page.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Grant_Solicitation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Draft, Open, or Closed. 

Draft: Solicitation creation and configuration stage. Nothing is exposed to the public. 
Open: Solicitation is open to the public and visible on the Current Funding Opportunities website.
Closed: Solicitation is closed and nDraft, Open, or Closed. 
Draft: Solicitation creation and configuration stage. Nothing is exposed to the public. 
Open: Solicitation is open to the public and visible on the website.
Closed: Solicitation is closed and not visible on the website.ot visible on the Current Funding Opportunities website.Solicitations Status is set to &quot;Closed&quot; automatically exactly at 5 pm on the day of the latest round due date. 
 A change mod is needed to set it back to open.

Canceled status SF-30800</description>
    <inlineHelpText>Draft: Creation and config stage. Nothing is shown to the public. 
Open: Open to the public and visible on website.
Closed: Closed and not visible on the website.Closed automatically at 3pm on the day of the latest round due date. Change mod to re-open</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard__c/Scorecard__c.object-meta.xml
<CustomObject>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard__c/fields/Assign_To_User__c.field-meta.xml
<CustomField>
    <fullName>Assign_To_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scorecard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Grant_Solicitation__c.field-meta.xml
<CustomField>
    <fullName>Grant_Solicitation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant/Solicitation</label>
    <referenceTo>Grant_Solicitation__c</referenceTo>
    <relationshipLabel>Scorecard</relationshipLabel>
    <relationshipName>Scorecard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <default>true</default>
                <label>Manual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Scorecard</relationshipLabel>
    <relationshipName>Scorecard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Scoring_Type__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Type__c</fullName>
    <label>Scoring Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Score Questions</fullName>
            </value>
            <value>
                <fullName>Score Answers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Metric__c/Scorecard_Metric__c.object-meta.xml
<CustomObject>
    <label>Scorecard Metric</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Scorecard Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Metric</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Metric__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Field Enablement</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Adoption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Metric__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>TextArea</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Metric__c/fields/Layout_Type__c.field-meta.xml
<CustomField>
    <fullName>Layout_Type__c</fullName>
    <label>Layout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Metric__c/fields/Maximum_Points__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Points__c</fullName>
    <label>Maximum Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scorecard_Metric__c/fields/Question_Description__c.field-meta.xml
<CustomField>
    <fullName>Question_Description__c</fullName>
    <label>Question Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scorecard_Metric__c/fields/Scorecard__c.field-meta.xml
<CustomField>
    <fullName>Scorecard__c</fullName>
    <label>Scorecard</label>
    <referenceTo>Scorecard__c</referenceTo>
    <relationshipLabel>Scorecard Metric</relationshipLabel>
    <relationshipName>Scorecard_Metric</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Proposal_TriggerHandler_Helper.cls
/*
Owner : MTX
Createddate : 15th Feb 2022
Modifieddate : 15th Feb 2022
Comments : this class is the helper of Proposal_TriggerHandler class.
*/
public class Proposal_TriggerHandler_Helper {
    
    //This method generates scorecards for group members on the proposal, when proposal is moved to Under Reveiw stage.
    public static void copyScorecardOnUnderReview(List<Proposal__c> newProjectList,Map<Id,Proposal__c> oldProjectMap) {
        Savepoint sp = Database.setSavepoint();
        try{
            Set<Id> setOfProposalIdsToGenerateScorecard = new Set<Id>();
            Set<Id> setOfGrantIdsToFetchScorecard = new Set<Id>();
            Set<Id> setOfGroupIdsToFetchMemeber = new Set<Id>();
            for(Proposal__c objProposal : newProjectList) {
                if(objProposal.Status__c != oldProjectMap.get(objProposal.Id).Status__c && objProposal.Status__c =='Under Review' && objProposal.Grant_Solicitation_Group__c!=null) {
                    setOfGrantIdsToFetchScorecard.add(objProposal.Grant_Solicitation__c);
                    setOfProposalIdsToGenerateScorecard.add(objProposal.Id);
                    setOfGroupIdsToFetchMemeber.add(objProposal.Grant_Solicitation_Group__c);
                }
            }
            if(setOfProposalIdsToGenerateScorecard.isEmpty()){
                return;
            }
            Map<Id,List<Scorecard__c>> mapOfGrantToScorecards = new Map<Id,List<Scorecard__c>>();
            for(Scorecard__c objScorecard : [Select Id ,Name ,Assign_To_User__c ,Description__c ,Grant_Solicitation__c ,IsActive__c ,
                                             Origin__c ,Proposal__c ,Scoring_Type__c ,Status__c,(Select Id,Answer__c ,Category__c ,Field_Type__c ,Layout_Type__c ,Maximum_Points__c ,Points__c ,Question_Description__c ,Scorecard__c ,Sequence_Order__c from Scorecard_Metric__r)  from Scorecard__c where Grant_Solicitation__c=:setOfGrantIdsToFetchScorecard and IsActive__c=true]) {
                                                 if(!mapOfGrantToScorecards.containskey(objScorecard.Grant_Solicitation__c)) {
                                                     mapOfGrantToScorecards.put(objScorecard.Grant_Solicitation__c,new List<Scorecard__c>());
                                                 }	    
                                                 mapOfGrantToScorecards.get(objScorecard.Grant_Solicitation__c).add(objScorecard);
                                             }
            System.debug('mapOfGrantToScorecards::'+mapOfGrantToScorecards);
            Map<Id,Grant_Solicitation_Group__c> mapGrantSolicitationGroup = New Map<Id,Grant_Solicitation_Group__c>([Select Id,(Select Id, Grant_Solicitation_Review_Team__c , Grant_Solicitation_Review_Team__r.Member__c from Grant_Solicitation_Group_Members__r where Grant_Solicitation_Review_Team__r.Scoring_Committee__c=true) from Grant_Solicitation_Group__c where Id=:setOfGroupIdsToFetchMemeber]);
            System.debug('mapGrantSolicitationGroup::'+mapGrantSolicitationGroup);
            Map<Id,List<Scorecard__c>> mapScoreToInsertForProposal = new Map<Id,List<Scorecard__c>>();
            List<Scorecard__c> listScoreToInsertForProposal = new List<Scorecard__c>();
            Map<Id,List<Scorecard_Metric__c>> mapIdToListScoreMatric = new Map<Id,List<Scorecard_Metric__c>>();
            for(Proposal__c objProposal : newProjectList) {
                if(setOfProposalIdsToGenerateScorecard.contains(objProposal.Id)) {
                    List<Scorecard__c> lstScore = mapOfGrantToScorecards.containskey(objProposal.Grant_Solicitation__c) ? mapOfGrantToScorecards.get(objProposal.Grant_Solicitation__c) : New List<Scorecard__c>();
                    System.debug('lstScore::'+lstScore);
                    for(Scorecard__c objScorecard : lstScore) {
                        Grant_Solicitation_Group__c objGrantSolicitationGroup = mapGrantSolicitationGroup.containskey(objProposal.Grant_Solicitation_Group__c) ? mapGrantSolicitationGroup.get(objProposal.Grant_Solicitation_Group__c) : New Grant_Solicitation_Group__c();
                        for(Grant_Solicitation_Group_Member__c objGSGM : objGrantSolicitationGroup.Grant_Solicitation_Group_Members__r) {
                            Id scoreId = objScorecard.Id;
                            Scorecard__c objScorecardToAdd = objScorecard.clone(false,false,false,false);
                            objScorecardToAdd.ParentScorecardId__c = objScorecard.Id;
                            objScorecardToAdd.Grant_Solicitation__c = null;
                            objScorecardToAdd.Proposal__c = objProposal.Id;
                            objScorecardToAdd.Scoring_Type__c = 'Score Answers';
                            objScorecardToAdd.OwnerId = objGSGM.Grant_Solicitation_Review_Team__r.Member__c;
                            objScorecardToAdd.Assign_To_User__c = objGSGM.Grant_Solicitation_Review_Team__r.Member__c;
                            listScoreToInsertForProposal.add(objScorecardToAdd);
                            /*if(!mapScoreToInsertForProposal.containskey(scoreId)) {
                                mapScoreToInsertForProposal.put(scoreId,new List<Scorecard__c>());
                            }
                            mapScoreToInsertForProposal.get(scoreId).add(objScorecardToAdd);*/
                        }
                        mapIdToListScoreMatric.put(objScorecard.Id,objScorecard.Scorecard_Metric__r);
                    }
                    System.debug('mapScoreToInsertForProposal::'+mapScoreToInsertForProposal);
                }
            }
            
            /*if(!mapScoreToInsertForProposal.isEmpty()){
                for(Id key: mapScoreToInsertForProposal.keySet()) {
                    listScoreToInsertForProposal.addAll(mapScoreToInsertForProposal.get(key));
                }
                insert listScoreToInsertForProposal;
            }*/
            if(!listScoreToInsertForProposal.isEmpty()) {
                insert listScoreToInsertForProposal;
            }
            
            Map<Id,Id> mapOfNewIdOldId = new Map<Id,Id>();
            for(Scorecard__c objScore : listScoreToInsertForProposal) {
                mapOfNewIdOldId.put(objScore.Id,objScore.ParentScorecardId__c); 
            }
            
            List<Scorecard_Metric__c> lstSCMToInsert = new List<Scorecard_Metric__c>();
            for(Id key:mapOfNewIdOldId.keySet()) {
                Id oldId = mapOfNewIdOldId.get(key);
                for(Scorecard_Metric__c objSCM : mapIdToListScoreMatric.get(oldId)){
                    Scorecard_Metric__c newRec = objSCM.clone(false,false,false,false);
                    newRec.Scorecard__c = key;
                    lstSCMToInsert.add(newRec);
                }
            }
            if(!lstSCMToInsert.isEmpty()) {
                insert lstSCMToInsert;
            }
            /*System.debug('listScoreMatricToInsert::'+listScoreMatricToInsert);
            for(Scorecard_Metric__c objSCM : listScoreMatricToInsert) {
                objSCM.Id=null;
                objSCM.Scorecard__c = mapScoreToInsertForProposal.get(objSCM.Scorecard__c).Id;
            }
            if(!listScoreMatricToInsert.isEmpty()){
                insert listScoreMatricToInsert;
            }*/
        } catch(Exception exp){
            Database.rollback(sp);
            newProjectList[0].addError('Failed to create Scorecard due to follwing reason: '+exp.getMessage());
        }
    }
}